* Kick Girl
** Kick Girl People
*** /Arcadia/ deput general of the Crusaders
*** /Stalker of Babylon/ probably related to Mystery Babylon
*** /Delilah/ Kick calls her "Little Flower"
*** /Ms J/ sister of Six
*** /Raz/ Recordkeeper for Arana and the Crusaders
    http://www.kick-girl.com/?p=1463
*** /Red/
*** /Uriel/ Archangel, guardian of the pit, obliterated by Delilah
    http://www.kick-girl.com/?p=2096
*** /Wynter/ Captain of the ship stolen by Kick and Delilah.
*** The devils etc.
**** /Adrian/ the antichrist, the lord of light
**** /Gog and Magog/
     http://www.kick-girl.com/?p=2427
**** /Judas/ becomes Famine
**** /Lilith/ now wife of Adrian
**** /Lucifer/
**** /Teko/ Little vampire demon working for Lilith
     http://www.kick-girl.com/?p=2763
**** /War/ used to be Ra.
*** The new twelve
**** /: Mika/ girl, black, dark hair, ??? eyes, killed by Teko
     http://www.kick-girl.com/?p=2196
**** /Cupid:/ girl, black, brown hair, pale blue eyes
**** /Flora: Mari/ Old lady, grey hair, pale blue eyes
**** /Indra:/ girl, white, blonde hair, pale blue eyes
**** /JJ: Anara/ girl, light brown hair,   orange eyes
**** /Muse:/ girl, brown, red hair, dark blue eyes
**** /Osyrus: Darren/ boy, white, grey hair, grey eyes, killed by Teko
     http://www.kick-girl.com/?p=2180
     http://www.kick-girl.com/?p=2763
     http://www.kick-girl.com/?p=2197
**** /Shield:/ guy, brown, brown hair, brown eyes
**** /Solar:/ man, black, no hair, violet eyes
**** /Sword:/ girl, white, black hair, pale grey eyes
**** /Zu: Sarah/ girl, white, brown hair, grey eyes
     http://www.kick-girl.com/comics/2016-09-05-KG-315.jpg
     http://www.kick-girl.com/?p=2811
*** The old NIJI ROKU (Rainbow Six)
**** /JJ/
     http://www.kick-girl.com/?p=2453
     http://www.kick-girl.com/?p=2176
     http://www.kick-girl.com/?p=2453
**** /Sumire/ Girlfriend of JJ, assassin for hire, killed by Kick
     http://www.kick-girl.com/?p=2453
     http://www.kick-girl.com/?p=2176
*** The old twelve
**** /Cupid/
**** /Pulsar/
**** /Ra/ becomes War
**** /Solar/
**** /Indra/
**** /Shield/
**** /Sword/
**** /Flora/
**** /Zu/
**** /SuperVee/ becomes Vesta
** /KG: 0026/ Kick says her mother is Vesta
   http://www.kick-girl.com/?p=175
** /KG: 0033/ Zero persuades Kick by squirting her
   http://www.kick-girl.com/?p=220
** /KG: 0001/ Kick draws on ground herself and KB holding hands
   http://www.kick-girl.com/?p=77
** /KG: 0039/ Kick says that Vesta was not there for her when she needed saving
   http://www.kick-girl.com/?p=268
** /KG: 0043/ Kick says she used to be called Kick Girl
   http://www.kick-girl.com/?p=280
** /KG: 0044 110415/ Kick as "The Monster" kills JJ on top of the demon pit
   http://www.kick-girl.com/?p=294
** /KG: 0047 110425/ JJ makes Kick promise she won't free KB as he is the worst
   http://www.kick-girl.com/?p=309
** /KG: 0054 110520/ Anara tells Kick she hears music/
   http://www.kick-girl.com/?p=333
** /KG: 0095 120514/ Kick, Zero, Judas find statues of JJ with sword
   http://www.kick-girl.com/?p=713
** /KG: 0098 120611/ Old time Kick in Fallout Temple with Red, Super Vee is her mother
   http://www.kick-girl.com/?p=748
** /KG: 0116 121112/ Judas call Kick "Six" to stop her demon form
   http://www.kick-girl.com/?p=906
** /KG: 0125 130107/ Kick says only one other than Zero could control the monster
   http://www.kick-girl.com/?p=942
** /KG: 0129 130204/ Kick says Super Vee was never there for her or her sisters
   http://www.kick-girl.com/?p=966
** /KG: 0130 130211/ Judas asks about Kick's father
   http://www.kick-girl.com/?p=972
** /KG: 0133 130304/ Kick saved from the pit by Red, and cannot save KillBoy 
   http://www.kick-girl.com/?p=982
** /KG: 0144 130520/ Kick and Zero find the atomic bomb craters
   http://www.kick-girl.com/?p=1282
** /KG: 0147 130610/ Kick kisses Zero and likes it
   http://www.kick-girl.com/?p=1298
** /KG: 0154 130729/ Kick on the seal notices Judas has the mark
   http://www.kick-girl.com/?p=1332
** /KG: 0156 130812/ Judas kisses Kick and kills her, and the demon's blood opens the seal
   http://www.kick-girl.com/?p=1340
** /KG: 0163 130923/ The Pit open and Lilith comes out and Adrian appears
   http://www.kick-girl.com/?p=1383
** /KG: 0166 131021/ Kick in game uses name "Lady Feylyn" playing with KB.
   http://www.kick-girl.com/?p=1405
** /KG: 0170 131118/ Anara and Raz fight watched by Arcadia
   http://www.kick-girl.com/?p=1443
** /KG: 0178 140120/ Anara says that the dragon is the devil
   http://www.kick-girl.com/?p=1524
** /KG: 0180 140203/ Lilith appears and tells demon to sabotage Anara
   http://www.kick-girl.com/?p=1549
** /KG: 0181 140210/ Judas says that Adrian is actually the Lord Of The Light
   http://www.kick-girl.com/?p=1554
** /KG: 0182 140217/ Adrian says he is Death in the Apocalypse
   http://www.kick-girl.com/?p=1560
** /KG: 0183 150224/ Kick says to spare Delilah, and Adrian just marks her
   http://www.kick-girl.com/?p=1565
** /KG: 0190 140414/ KillBoy wants to kill Kick and himself
   http://www.kick-girl.com/?p=1610
** /KG: 0202 140707/ Red asks Kick to join, she refuses and he becomes adult
   http://www.kick-girl.com/?p=1684
** /KG: 0203 140714/ Red explains the marks
   http://www.kick-girl.com/?p=1689
** /KG: 0204 140721/ Red tells Kick to find Heaven's new champion
   http://www.kick-girl.com/?p=1689
** /KG: 0211 140908/ Delilah saves Kick from KB
   http://www.kick-girl.com/?p=1775
** /KG: 0212 140915/ Six tells JJ that she could be Sidekick Girl
   http://www.kick-girl.com/?p=1791
** /KG: 0215 141006/ KB mentions her parents secret and she says the 12 assholes
   http://www.kick-girl.com/?p=1807
** /KG: 0217 141020/ Red as adult gives mark, holy water, costume to Zero
   http://www.kick-girl.com/?p=1811
** /KG: 0222 140924/ Annoying black demon in cathedral following Anara
   http://www.kick-girl.com/?p=1848
** /KG: 0245 150504/ Kick shows relics of the 12 superheroes including Solar Core
   http://www.kick-girl.com/?p=2069
** /KG: 0247 150518/ Kick scolds Delilah for looking more like a slut
   http://www.kick-girl.com/?p=2072
** /KG: 0248 150525/ Kick celebrates that Delilah is jealous, they used to be close
   http://www.kick-girl.com/?p=2073
** /KG: 0252 150622/ Kick says that Adrian is the antichrist
   http://www.kick-girl.com/?p=2086
** /KG: 0256 150720/ Arechangel Uriel cannot harm them because mark of God.
   http://www.kick-girl.com/?p=2100
** /KG: 0256 150720/ There is no angel called "Red"
   http://www.kick-girl.com/?p=2100
** /KG: 0258 150803/ Delilah gets Cupid's bow
   http://www.kick-girl.com/?p=2102
** /KG: 0260/ Flashback to before the apocalypse with Sumire, JJ, K-Scum
   http://www.kick-girl.com/?p=2176
** /KG: 0259 150810/ K-Scum mentions Kick's sister, MS. J, made a film about her
   http://www.kick-girl.com/?p=2175
** /KG: 0264/ One of the 12 names the Osyrus, Shield, Sword. Mika is dead
   http://www.kick-girl.com/?p=2180
** /KG: 0266/ Anara finds first killed of the twelve
   http://www.kick-girl.com/?p=2196
** /KG: 0270/ Cupid's bow is one of several. Also it obliterated the archangel Uriel
   http://www.kick-girl.com/?p=2216
** /KG: 0276/ Kick says don't kill KB becase they share the same soul
   http://www.kick-girl.com/?p=2276
** /KG: 0289/ Delilah talks with witch about black mark
   http://www.kick-girl.com/?p=2361
** /KG: 0290 160314/ The witch is Lilith
   http://www.kick-girl.com/?p=2368
** /KG: 0300/ Kick fights Wynter who sees her eyes are red
   http://www.kick-girl.com/?p=2414
** /KG: 0305/ Adrian waits for Red and they love each other
   http://www.kick-girl.com/?p=2428
** /KG: 0306/ Flashback to just after the sealing, JJ, Sumire and Pulsar at the Pit
   http://www.kick-girl.com/?p=2453
** /KG: 0309/ Red appears when JJ wants to attack Kick at the Pit
   http://www.kick-girl.com/?p=2462
** /KG: 0311/ Red says all mortal people who attempt to kill her will die
   http://www.kick-girl.com/?p=2496
** /KG: 0338/ "War" appears and mentions Sumire and the Niji-Roku
   http://www.kick-girl.com/?p=2640
** /KG: 0369/ Teko says that Lilith would spare Six and Adrian too
   http://www.kick-girl.com/?p=2773
** /KG: 0369/ Lilith says the female one as "Pestilence" and the one with the hat as "Death"
   http://www.kick-girl.com/?p=2780
** /KG: 0370/ Lilith refers to Adrian as "Conquest".
   http://www.kick-girl.com/?p=2784
** /KG: 0371/ Lilith says her husband Lucifer wold not approve but is distracted.
   http://www.kick-girl.com/?p=2796
** /KG: 0372/ Teko says to Kick she met Lilith when she was Six
   http://www.kick-girl.com/?p=2797
** /KG: 0375/ The councillors name themselves
   http://www.kick-girl.com/?p=2810
** /KG: 0378/ Kick and Anara have a good moment and they hear music when around
   http://www.kick-girl.com/?p=2816
** /KG: 0395/ Judas refers to Adam as his father.
   http://www.kick-girl.com/?p=2879
